const KEY = "MayTrangSatsBoy";

/**
 * Encrypts a string using a simple XOR cipher with the key "MayTrangSatsBoy"
 * and outputs a hex string representation of the character codes.
 */
export const encrypt = (text: string): string => {
  if (!text) return "";
  let result = "";
  for (let i = 0; i < text.length; i++) {
    const charCode = text.charCodeAt(i) ^ KEY.charCodeAt(i % KEY.length);
    // Convert character code to 4-digit hex to handle unicode/emoji correctly
    result += charCode.toString(16).padStart(4, "0");
  }
  return result;
};

/**
 * Decrypts a hex string generated by the encrypt function using the same XOR cipher.
 */
export const decrypt = (hexStr: string): string => {
  if (!hexStr) return "";
  try {
    let decryptedText = "";
    for (let i = 0; i < hexStr.length; i += 4) {
      const hexPart = hexStr.substring(i, i + 4);
      const charCode = parseInt(hexPart, 16);
      decryptedText += String.fromCharCode(charCode);
    }

    let originalText = "";
    for (let i = 0; i < decryptedText.length; i++) {
      const charCode = decryptedText.charCodeAt(i) ^ KEY.charCodeAt(i % KEY.length);
      originalText += String.fromCharCode(charCode);
    }
    return originalText;
  } catch (error) {
    console.error("Failed to decrypt data:", error);
    return "";
  }
};
